### ISSUE TITLE
[Investigation] Docker file too large

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#30]
Current Docker file is too large (2.4GB). I am not a docker expert and would like for someone to weigh in and either find the root cause or validate that the size is correct. Thanks in advance.

Reproduction:
Pull the latest version of repo
run `docker compose up`
Check docker image size of vidur_app (this excludes size of postgres)

**Comment by amandesai01** [comment]
@akashvarun10 maybe you can help?

**Comment by akashvarun10** [comment]
I will check it out.

**Comment by akashvarun10** [comment]
The `vidur_app` container fails to start due to a missing `drizzle-kit` command, and I was not able to run with your changes. The env should be created manually even still it throws errors.

Yes, docker size is large because it could be due to inefficient Cacheing Dockerfile layers, unnecessary files in the build context, and build cached files. 

### Pull Request Comment

I found a fix for the large Docker image size issue by using a multi-stage build. 

**Fix Explanation:**
1. **Builder Stage:** We use a `node:18.20-alpine` image to install dependencies and copy the application files.
2. **Production Stage:** We start with a fresh `node:18.20-alpine` image and only copy the necessary files from the builder stage.

This approach reduces the final image size to 400MB by excluding unnecessary build files and artifacts, resulting in a more efficient Docker image.

If that's ok I will open a Pull Request , With the new files as `Dockerfile.dev` and `docker-compose-prod.yaml`, keeping the old feels and this version can be used as Production version. But we need to change it once the app is done

**Comment by amandesai01** [comment]
Got it, so you mean to say we should do this for prod and it would be okay to keep large size in dev, correct? Can someone validate if dev mode has similar sized docker containers?

**Comment by akashvarun10** [comment]
Ok sure, I'll update it by tonight

**Comment by akashvarun10** [comment]
The Development version which the changes are made after i pushed is not working and throwing errors .. Can. you check if it's the same with you as well @amandesai01

**Comment by amandesai01** [comment]
Nope. Can you show what error you getting?

**Comment by akashvarun10** [comment]
My bad it's working fine. I've made changes to prod files please check on that

**Comment by manasgandhi99** [comment]
@akashvarun10 I was trying to run the changes done locally. But the image size stays the same. Can you help me to understand where did I go wrong?

**Comment by akashvarun10** [comment]
@manasgandhi99 Yeah, the production version is not merged yet to the main branch. So, Once it's done you can run it.

**Comment by PradeepKumar8765** [comment]
Hello team Can I take up this docker file issue?
